# Generated by Django 5.1.3 on 2025-02-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
