# Generated by Django 5.1.3 on 2025-03-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=9),
        ),
    ]
